# Site
repository: jesmaail.jesmaail.github.io
favicon: assets/images/favicon.ico
baseurl: #TODO

# Content configuration version
version: 2

# Personal info
name: Joseph Esmaail
title: Software Engineer
email: dev(at)esmaail.com
# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: jesmaail
github_username:  jesmaail
linkedin_username: jesmaail
# youtube_username: maybe later?

# Additional icon links
additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: assets/images/profile.jpg
# about_content: | # this will include new lines to allow paragraphs
#   This content is now in the about override file under _includes

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - MiniPaintPal.md
      - Sharponzo.md
      - DeciGames.md

# # Footer
# footer_show_references: true
# references_title: CV and References available on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  
plugins:
 - jekyll-seo-tag
